/**
 * LessonContentExtra.ts — Content for 17 new chapters (6 beginner, 5 intermediate, 6 advanced)
 */
export const EXTRA_CONTENT: Record<string, string> = {
  stock_market: 'The stock market is a marketplace where people buy and sell ownership in companies. When a company needs money to grow, it sells shares to the public.\n\nThere are two major US exchanges: NYSE and NASDAQ. Together they list over 6,000 companies worth more than $40 trillion.\n\nStock prices move on supply and demand. More buyers than sellers means price goes up. Long-term, prices reflect actual business performance.\n\nThe US stock market has returned about 10% per year historically. $10,000 invested in 1990 would be worth over $170,000 today.\n\nYou do not need to pick stocks. Most professionals fail to beat the market. Index ETFs are the smartest move. Not financial advice.',

  first_paycheck: 'Your first paycheck will be smaller than expected. Gross pay is before deductions. Net pay is what hits your bank account after taxes, Social Security, Medicare.\n\nExpect to take home 70-80% of gross pay. A $50,000 salary means about $35,000-40,000 actual take-home.\n\nYour W-4 form controls tax withholding. More allowances means more now but possible tax bill later. Fewer means a refund.\n\nIf your employer offers 401k match, contribute at least enough to get the full match. That is an instant 50-100% return.\n\nThe 50/30/20 rule: 50% needs, 30% wants, 20% savings and investing. Not financial advice.',

  starting_early: 'The most powerful investing force is not intelligence or income. It is time. Starting 10 years earlier is worth more than doubling your contribution.\n\nSarah invests $200/month from 22 to 32 then stops. Mike invests $200/month from 32 to 65. At 8%, Sarah has more money despite investing 23 fewer years.\n\nEvery year you wait costs decades of compounding. A 25-year-old who delays 5 years loses exponential growth on every future dollar.\n\n$25 per week at 8% over 40 years becomes $380,000. The amount matters less than starting immediately.\n\nThe perfect time to start was yesterday. The second best time is right now. Not financial advice.',

  inflation: 'Inflation means $100 today buys less than $100 ten years from now. Average annual inflation is 2-3%, which sounds small until it compounds.\n\nAt 3% inflation, prices double every 24 years. Coffee that costs $5 today will cost $10 in 2048.\n\nMoney in a 0.5% savings account is losing purchasing power every year. After inflation, you earn negative real returns.\n\nThe stock market returns about 10% nominally, roughly 7% after inflation. Your purchasing power doubles every 10 years.\n\nInvesting is not optional for building wealth. Cash in savings slowly makes you poorer. Not financial advice.',

  emergency_fund: 'Before investing, build an emergency fund of 3-6 months expenses in a high-yield savings account, separate from investments.\n\nWithout one, any unexpected expense forces you to sell investments. Markets often drop during recessions when people lose jobs.\n\nCalculate monthly expenses: rent, utilities, food, transport, minimum debt payments. Multiply by 3 for a starter fund, 6 for security.\n\nHigh-yield savings accounts offer 4-5% interest. Ally Bank and Marcus are popular options. Your emergency fund should earn something.\n\nOnly after your emergency fund is complete should you focus on investing. Not financial advice.',

  debt_types: 'Not all debt is equal. Bad debt buys things that lose value: credit cards at 15-25%, car loans you cannot afford, personal loans for vacations.\n\nGood debt buys appreciating assets: mortgages, student loans for high-earning degrees, business loans. A mortgage at 7% on a home appreciating at 3-4% is fundamentally different.\n\nRule of thumb: pay off any debt above 7% before investing. Below 7%, the stock market historically outperforms the interest cost.\n\nA $5,000 credit card balance at 20% costs $1,000 per year in interest alone. That money could be compounding in your portfolio.\n\nUse the Debt Repayment Planner for Avalanche and Snowball strategies. Not financial advice.',

  dca: 'Dollar-cost averaging means investing a fixed amount at regular intervals regardless of market conditions.\n\nWhen you invest $100/week, you buy more shares when cheap and fewer when expensive. Your average cost tends to be lower than the average price.\n\nThis removes emotion from investing. No timing, no charts, no decisions. Research shows automatic investors outperform discretionary traders.\n\nDuring the March 2020 crash, automatic investors bought shares at massive discounts. Those shares doubled in value the following year.\n\nMy Frontier recommends weekly contributions based on your budget surplus. Set up automatic transfers. Not financial advice.',

  balance_sheet: 'A balance sheet shows what a company owns (assets), owes (liabilities), and what remains for owners (equity). Assets always equal Liabilities plus Equity.\n\nKey assets: cash and equivalents (liquidity), accounts receivable (money owed to them), property and equipment. Cash-heavy companies weather downturns.\n\nKey liabilities: accounts payable, short-term debt, long-term debt. The debt-to-equity ratio measures leverage. High ratios are dangerous in recessions.\n\nFor ETF investors, understanding balance sheets helps evaluate whether companies inside your ETFs are financially sound.\n\nQuality factor ETFs like QUAL specifically weight companies with healthy balance sheets. Not financial advice.',

  pe_ratio: 'The P/E ratio divides stock price by annual earnings per share. A P/E of 20 means paying $20 for every $1 of earnings.\n\nThe S&P 500 historical average P/E is about 15-16. Above 20 is expensive relative to history. Below 15 is cheap.\n\nHigh P/E is not always bad. Growth companies like Amazon trade at 50-100+ because investors pay for future earnings growth.\n\nLow P/E can be a trap. A company at P/E 5 might be cheap for good reason: declining business, legal problems, fading industry.\n\nGrowth ETFs like QQQ trade at higher P/E than value ETFs like VTV. Higher P/E means higher expectations and risk. Not financial advice.',

  dividends: 'A dividend is cash paid by a company to shareholders, usually quarterly. Dividend ETFs provide income just for holding them.\n\nDividend yield is annual payment divided by price. A $100 stock paying $4/year yields 4%. SCHD currently yields about 3.5%.\n\nDividend growth beats high yield. A company growing dividends 10%/year from a 2% base is better than a 6% payer that cuts in recession.\n\nDividend reinvestment (DRIP) creates a snowball: dividends buy more shares, which generate more dividends, which buy more shares.\n\nDividend ETFs like SCHD and VYM diversify across dozens of dividend-paying companies. Not financial advice.',

  sector_rotation: 'Different sectors perform better at different economic cycle stages. Expansion favors tech. Peak favors energy. Contraction favors healthcare. Recovery favors financials.\n\nThis sounds simple but is extremely difficult to execute. Predicting the economic cycle is hard. Timing rotations is harder.\n\nMost research shows individual investors attempting sector rotation underperform simple index investing over time.\n\nThe value is understanding WHY your portfolio performs as it does, not trading based on cycle predictions.\n\nMy Frontier allows diverse sector selection that naturally smooths sector rotation impact. Not financial advice.',

  options_basics: 'An option is a contract giving the right to buy (call) or sell (put) 100 shares at a specific price before a specific date.\n\nCall options profit when stocks rise above the strike price. Put options profit when stocks fall below it.\n\nOption pricing depends on intrinsic value, time value, and implied volatility. The Black-Scholes model revolutionized pricing in 1973.\n\nSelling covered calls on ETFs you own is relatively conservative. Buying naked options is extremely speculative.\n\n90% of options expire worthless. For most retail investors, options should be used cautiously if at all. Not financial advice.',

  tax_loss: 'Tax-loss harvesting means selling investments at a loss to offset capital gains elsewhere, then buying a similar replacement.\n\nIf you have $10,000 in gains and $7,000 in harvested losses, you only pay tax on $3,000 net gain. Unused losses carry forward.\n\nThe wash-sale rule prevents buying the same security within 30 days. Sell VTI, buy ITOT instead: same exposure, no wash sale.\n\nHarvesting a $10,000 loss at 25% tax rate saves $2,500 in taxes. That $2,500 stays invested and compounds.\n\nOnly harvest in taxable accounts, not IRAs or 401ks. Consult a tax advisor for your situation. Not financial advice.',

  factor_investing: 'Factor investing tilts your portfolio toward attributes that research shows generate higher returns: value, size, quality, momentum, low volatility.\n\nFama and French showed value and size factors explain return differences. Subsequent research added quality, momentum, profitability.\n\nFactor ETFs: QUAL (quality), VTV (value), AVUV (small-cap value), MTUM (momentum). These can be combined for systematic outperformance.\n\nThe catch: factor premiums can go years without working. Value badly underperformed growth 2010-2020 but recovered strongly in 2022.\n\nFactor investing requires conviction and a long time horizon. Not financial advice.',

  rebalancing: 'Rebalancing returns your portfolio to target allocation after market drift. If your 70/30 stock/bond target became 80/20, sell stocks and buy bonds.\n\nThis enforces selling high and buying low automatically. Two approaches: calendar (annually) or threshold (when any allocation drifts 5%+).\n\nTax tip: rebalance using new contributions to avoid selling. Put new money into underweighted assets. Rebalance inside tax-advantaged accounts.\n\nOptimal frequency is roughly annual or when allocations drift more than 5-10%. More frequent trading generates unnecessary costs.\n\nMy Frontier portfolios should be reviewed every 90 days to stay aligned with current market conditions. Not financial advice.',

  bonds_advanced: 'Duration measures a bond sensitivity to interest rate changes. A duration-8 bond loses 8% when rates rise 1%. TLT (20+ year Treasuries) has duration 17+.\n\nThe yield curve shows rates at different maturities. Normally longer-term bonds pay more. When short rates exceed long rates (inversion), recessions often follow.\n\nCredit spreads measure the yield difference between corporate and Treasury bonds. Widening spreads signal worry about defaults.\n\nFor most investors, intermediate-term bond ETFs like AGG or BND (duration 5-7 years) provide adequate stability without extreme rate sensitivity.\n\nAdding long-duration bonds dramatically increases risk in rising rate environments. Not financial advice.',

  alternatives: 'Alternative assets include real estate, commodities, hedge funds, crypto. Each offers different returns and correlation.\n\nREITs like VNQ hold apartments, offices, warehouses. Required to distribute 90% of income as dividends. Low correlation with stocks.\n\nGold (GLD) is an inflation hedge and safe haven. Oil (USO) rises with economic expansion. Both diversify portfolio risk.\n\nCrypto has extreme volatility with 80%+ drawdowns. Most advisors recommend 0-5% allocation for those who understand the risk.\n\nAlternatives should complement, not replace, your core stock/bond portfolio. Not financial advice.',
};
